# Generated by Django 4.1.5 on 2023-01-29 14:05

import backoffice.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first_name')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last_name')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('facebookId', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('android', models.BooleanField(blank=True, default=False)),
                ('ios', models.BooleanField(blank=True, default=False)),
                ('acceptPush', models.BooleanField(default=False)),
                ('pushToken', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_influenceur', models.BooleanField(default=False, verbose_name='influenceur')),
                ('valid', models.BooleanField(default=True, verbose_name='valid')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', backoffice.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameActivity', models.CharField(blank=True, max_length=50, verbose_name='nameActivity')),
                ('isTakeAway', models.BooleanField(default=False, verbose_name='isTakeAway')),
                ('isOnSit', models.BooleanField(default=False, verbose_name='isOnSit')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(blank=True, max_length=250, verbose_name='address1')),
                ('address2', models.CharField(blank=True, max_length=50, null=True, verbose_name='address2')),
                ('address3', models.CharField(blank=True, max_length=50, null=True, verbose_name='address3')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='state')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='country')),
                ('postalCode', models.CharField(blank=True, max_length=5, verbose_name='postalCode')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descriptionOffer', models.CharField(blank=True, max_length=300, verbose_name='descriptionOffer')),
                ('descriptionCondition', models.CharField(blank=True, max_length=300, verbose_name='descriptionCondition')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.activity')),
            ],
        ),
        migrations.CreateModel(
            name='TypeActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameTypeActivity', models.CharField(blank=True, max_length=50, verbose_name='nameTypeActivity')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(blank=True, verbose_name='status')),
                ('dateReservation', models.DateTimeField(null=True, verbose_name='dateReservation')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fromDate', models.CharField(blank=True, max_length=15, verbose_name='fromDate')),
                ('toDate', models.CharField(blank=True, max_length=15, verbose_name='toDate')),
                ('startDate', models.CharField(blank=True, max_length=15, verbose_name='startDate')),
                ('endDate', models.CharField(blank=True, max_length=15, verbose_name='endDate')),
                ('pauseStart', models.CharField(blank=True, max_length=15, verbose_name='pauseStart')),
                ('pauseEnd', models.CharField(blank=True, max_length=15, verbose_name='pauseEnd')),
                ('isOpen', models.BooleanField(default=False, verbose_name='isOpen')),
                ('isOrderBy', models.IntegerField(blank=True, verbose_name='isOrderBy')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameCompany', models.CharField(blank=True, max_length=50, null=True, verbose_name='nameCompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backoffice.address'),
        ),
        migrations.AddField(
            model_name='activity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.company'),
        ),
        migrations.AddField(
            model_name='activity',
            name='typeActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.typeactivity'),
        ),
    ]
