# Generated by Django 4.1.5 on 2023-02-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_alter_opening_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='nameOffer',
            field=models.CharField(blank=True, max_length=100, verbose_name='nameOffer'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(blank=True, max_length=800, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='descriptionCondition',
            field=models.CharField(blank=True, max_length=500, verbose_name='descriptionCondition'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='descriptionOffer',
            field=models.CharField(blank=True, max_length=500, verbose_name='descriptionOffer'),
        ),
    ]
