# Generated by Django 4.1.5 on 2023-03-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_offer_nameoffer_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgCompany',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('isPrincipal', models.BooleanField(default=False, verbose_name='isPrincipal')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompany',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameTypeCompany', models.CharField(blank=True, max_length=50, verbose_name='nameTypeCompany')),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='activity',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.address'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=800, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='company',
            name='isOnSit',
            field=models.BooleanField(default=False, verbose_name='isOnSit'),
        ),
        migrations.AddField(
            model_name='company',
            name='isTakeAway',
            field=models.BooleanField(default=False, verbose_name='isTakeAway'),
        ),
        migrations.AddField(
            model_name='offer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.company'),
        ),
        migrations.AddField(
            model_name='opening',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='backoffice.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nameCompany',
            field=models.CharField(blank=True, max_length=50, verbose_name='nameCompany'),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='TypeActivity',
        ),
        migrations.AddField(
            model_name='imgcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgCompany', to='backoffice.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='typeCompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.typecompany'),
        ),
    ]
