# Generated by Django 4.1.5 on 2023-03-19 16:35

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_imgcompany_typecompany_remove_offer_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgcompany',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=backoffice.models.upload_to),
        ),
    ]
