# Generated by Django 4.1.5 on 2023-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_alter_imgcompany_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isCompanyActif',
            field=models.BooleanField(default=True, verbose_name='isCompanyActif'),
        ),
    ]
