# Generated by Django 5.1.3 on 2025-03-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_offer_descriptioncondition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='typeCompany',
            new_name='type_company',
        ),
        migrations.RenameField(
            model_name='typecompany',
            old_name='nameTypeCompany',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='postalCode',
        ),
        migrations.RemoveField(
            model_name='company',
            name='isCompanyActif',
        ),
        migrations.RemoveField(
            model_name='company',
            name='isOnSit',
        ),
        migrations.RemoveField(
            model_name='company',
            name='isTakeAway',
        ),
        migrations.RemoveField(
            model_name='company',
            name='nameCompany',
        ),
        migrations.RemoveField(
            model_name='imgcompany',
            name='isPrincipal',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='isOpen',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='isOrderBy',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='pauseEnd',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='pauseStart',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='opening',
            name='toDate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='dateReservation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='company',
            name='is_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_onsit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_takeaway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='name_company',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='imgcompany',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opening',
            name='break_end',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='opening',
            name='break_start',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='opening',
            name='close_hour',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='opening',
            name='day',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='opening',
            name='id_day',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opening',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opening',
            name='open_hour',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tiktok',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(blank=True),
        ),
    ]
