# Generated by Django 5.1.3 on 2025-03-08 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_typecompany_company_type_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address1',
            new_name='address_principal',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address2',
            new_name='address_secondary',
        ),
    ]
