# Generated by Django 6.0.6 on 2026-06-07 20:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_company_to_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgvenue',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgVenue', to='api.venue'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
