# Generated by Django 6.0.6 on 2026-06-11 06:26

from django.db import migrations, models


def demote_duplicate_active_applications(apps, schema_editor):
    """Keep only the newest active (pending/accepted) application per
    (user, offer) pair; older ones are demoted to declined so the conditional
    unique constraint can be created. Pre-launch data only."""
    Reservation = apps.get_model('api', 'Reservation')
    from django.db.models import Count
    pairs = (Reservation.objects.filter(status__in=(0, 1))
             .values('user', 'offer')
             .annotate(n=Count('id')).filter(n__gt=1))
    for pair in pairs:
        actives = (Reservation.objects
                   .filter(user_id=pair['user'], offer_id=pair['offer'], status__in=(0, 1))
                   .order_by('-id'))
        ids_to_demote = list(actives.values_list('id', flat=True)[1:])
        Reservation.objects.filter(id__in=ids_to_demote).update(status=2)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_message_unread_emailed_at_and_more'),
    ]

    operations = [
        migrations.RunPython(demote_duplicate_active_applications, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', (0, 1))), fields=('user', 'offer'), name='unique_active_application'),
        ),
    ]
