# Generated by Django 6.0.6 on 2026-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_reservation_completed_at_reservation_no_show_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_active_application',
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 0)), fields=('user', 'offer'), name='unique_pending_application'),
        ),
    ]
