# Generated by Django 6.0.6 on 2026-06-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_reservation_unique_active_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='require_post_proof',
            field=models.BooleanField(default=False),
        ),
    ]
