# Generated by Django 6.0.6 on 2026-07-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_conversation_updated_at_mutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
